services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: psswd
      POSTGRES_DB: postgresDB
    volumes:
      - './src/migrations/:/docker-entrypoint-initdb.d/'
    command: ["postgres", "-c", "log_statement=all"]
    networks:
      - app-network

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: cinema_app
    ports:
      - "8082:8082"
    volumes:
      - .:/cinema
    restart: unless-stopped
    depends_on:
      - postgres    # Добавляем зависимость
    networks:
      - app-network

networks:    # Определяем сеть
  app-network:
    driver: bridge